# Site
name: "47billion"
remote_theme: 47billion/mediumish-theme-jekyll
description: "Building intelligent communities for a better tomorrow"
meta_description: "User experience and design, Analytics and Mobile application development."
logo: 'assets/images/47Billion.png'
favicon: 'assets/images/favicon.ico'
baseurl: "/blog"
production_url : https://47billion.github.io/blog
BASE_PATH : https://47billion.com/blog

google_analytics: 'UA-60258456-1'
disqus: '47billion-1'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Authors
authors:
  rajeev:
    name: Rajeev
    display_name: Rajeev
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: hello@47billion.com
    web: https://47billion.com
    twitter: https://twitter.com/47billion
    description: "I am a Co-founder and Chief Architect at 47Billion. We specialize in helping technology companies build awesome products. Contact us at info@47billion.com."
  atul:
    name: Atul
    display_name: Atul
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: hello@47billion.com
    web: https://www.47billion.com
    twitter: https://twitter.com/47billion
    description: "I am a technical lead for mobile app development at 47Billion. We specialize in helping technology companies build awesome products. Contact us at info@47billion.com."
  satish:
    name: Satish
    display_name: Satish
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: hello@47billion.com
    web: https://www.47billion.com
    twitter: https://twitter.com/47billion
    description: "I am a devops lead at 47Billion. We specialize in helping technology companies build awesome products. Contact us at info@47billion.com."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-remote-theme
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
