# Site
name: "47billion"
remote_theme: 47billion/mediumish-theme-jekyll
description: "47Billion official blog"
meta_description: "User experience and design, Analytics and Mobile application development."
logo: 'assets/images/47Billion.png'
favicon: 'assets/images/47Billion.png'
baseurl: "/blog"
production_url : https://47billion.github.io/blog
BASE_PATH : https://47billion.com/blog

google_analytics: 'UA-46278016-1'
disqus: '47billion-1'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Authors
authors:
  Rajeev:
    name: Rajeev
    display_name: Rajeev
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: hello@47billion.com
    web: https://47billion.com
    twitter: https://twitter.com/47billion
    description: "I am a Co-founder and Chief Architect at 47Billion.com. We specialize in helping technology companies build awesome products. Contact us at info@47billion.com."
  john:
    name: John
    display_name: John
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-remote-theme
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
